[workspace]
members = [ "chat",
    "concurrency",
    "ecos-system",
    "error-code",
    "error-code-derive",
    "macros", "notify-server",
    "rcli",
    "simple-redis",
]
resolver = "2"

[workspace.dependencies]
error-code = { path = "./error-code" }
error-code-derive = { path = "./error-code-derive" }
