###chat api test

### signup user
POST http://127.0.0.1:8002/api/signup
Content-Type: application/json
# x-request-id: dfasfds

{
    "workspace": "acme",
    "fullname": "iori" ,
    "email": "abd@ma.org",
    "password": "123456"
}


### signup user
POST http://127.0.0.1:8002/api/signup
Content-Type: application/json
# x-request-id: dfasfds

{
    "workspace": "acme",
    "fullname": "shiina" ,
    "email": "abe@ma.org",
    "password": "123456"
}

### signup user
POST http://127.0.0.1:8002/api/signup
Content-Type: application/json
# x-request-id: dfasfds

{
    "workspace": "acme",
    "fullname": "zuki" ,
    "email": "abf@ma.org",
    "password": "123456"
}

### signin user
# @name signin
POST http://127.0.0.1:8002/api/signin
Content-Type: application/json

{
    "email": "abd@ma.org",
    "password": "123456"
}

@token = {{signin.response.body.token}}


###
GET http://127.0.0.1:8002/api/chats
Authorization: Bearer {{token}}

### create chat
POST http://127.0.0.1:8002/api/chats
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "acme",
    "members": [1, 2],
    "public": false
}

### get chat
GET http://127.0.0.1:8002/api/chats/1
Content-Type: application/json
Authorization: Bearer {{token}}

###
PATCH  http://127.0.0.1:8002/api/chats/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "acme_update",
    "members": [1, 3],
    "public": false
}


###
DELETE http://127.0.0.1:8002/api/chats/1
Content-Type: application/json
Authorization: Bearer {{token}}


### get user list
GET http://127.0.0.1:8002/api/users
Authorization: Bearer {{token}}
Content-Type: application/json



### upload file
POST http://127.0.0.1:8002/api/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; filename="1.jpg"
Content-Type: application/octet-stream

< D:\\1.jpg

--MyBoundary
Content-Disposition: form-data; filename="hello.txt" Content-Type: text/plain

Hello, World!
--MyBoundary--

### get files
GET http://127.0.0.1:8002/api/files/1/50f/eb8/cf38e34a4da2990ca4a9a6c69bc3bc7f93.jpg
Authorization: Bearer {{token}}


### send a message
POST http://127.0.0.1:8002/api/chats/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "content": "Hello, World!",
    "files": []
}


### get messages
GET http://127.0.0.1:8002/api/chats/1/messages?limit=6&last_id=5
Authorization: Bearer {{token}}


