[package]
name = "chat-test"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
chat-core = { workspace = true }
chat-server = { workspace = true, features = ["test-util"] }
chat-notify-server = { workspace = true }
reqwest = { version = "0.12.12", default-features = false, features = [
    "rustls-tls",
    "json",
    "multipart",
    "stream",
] }
reqwest-eventsource = "0.6.0"
axum = "0.8.1"
tokio = "1.43.0"
anyhow = "1.0.95"
secrecy = { version = "0.10.3", features = ["serde"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
futures = "0.3.31"
