[package]
name = "taotie"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
chrono = { version = "0.4.39", features = ["serde"] }
arrow = { version = "54.2.1", features = ["prettyprint"] }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"
